name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Compile Java program
      run: javac src/test/CityTemperature.java

    - name: Run Java program
      run: java -cp src/test CityTemperature
