name: Java CI and CSV Merge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Utilisez 'temurin' ou une autre distribution compatible
        java-version: '22'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn clean test

  compile_and_run_java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Compile Java program
      run: javac -d out src/main/java/CityTemperature.java

    - name: Run Java program
      run: java -cp out CityTemperature

  csv_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Compile Java code for CSV merge
      run: |
        javac -d out src/task/GenerateCSV1.java
        javac -d out src/task/GenerateCSV2.java
        javac -d out src/task/GenerateCSV3.java
        javac -d out src/task/MergeCSVs.java

    - name: Generate CSV files
      run: |
        java -cp out GenerateCSV1
        java -cp out GenerateCSV2
        java -cp out GenerateCSV3

    - name: Merge CSV files
      run: |
        java -cp out MergeCSVs

    - name: Upload merged CSV
      uses: actions/upload-artifact@v3
      with:
        name: merged_data.csv
        path: merged_data.csv
