name: Java CI and CSV Merge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

  compile_and_run_java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Compile Java program
      run: javac -d out src/test/CityTemperature.java

    - name: Run Java program
      run: java -cp out CityTemperature

  csv_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'adopt'

    - name: Compile Java code for CSV merge
      run: |
        javac src/task/GenerateCSV1.java
        javac src/task/GenerateCSV2.java
        javac src/task/GenerateCSV3.java
        javac src/task/MergeCSVs.java

    - name: Generate CSV files
      run: |
        java -cp src/task GenerateCSV1
        java -cp src/task GenerateCSV2
        java -cp src/task GenerateCSV3

    - name: Merge CSV files
      run: |
        java -cp src/task MergeCSVs

    - name: Upload merged CSV
      uses: actions/upload-artifact@v2
      with:
        name: merged_data.csv
        path: merged_data.csv
