name: Java CI and CSV Merge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CSV_FILE_PATH: 'merged_data[1].csv'  # Variable d'environnement globale pour le chemin du fichier CSV

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn clean test

  compile_and_run_java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Compile Java program
      run: javac -d out src/main/CityTemperature.java src/main/MapReduceMain.java

    - name: Run CityTemperature
      run: java -cp out CityTemperature

    - name: Run MapReduce
      run: java -cp out MapReduceMain

  csv_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Compile Java code for CSV merge
      run: |
        javac -d out src/task/GenerateCSV1.java
        javac -d out src/task/GenerateCSV2.java
        javac -d out src/task/GenerateCSV3.java
        javac -d out src/task/MergeCSVs.java

    - name: Generate CSV files
      run: |
        java -cp out GenerateCSV1
        java -cp out GenerateCSV2
        java -cp out GenerateCSV3

    - name: Merge CSV files
      run: |
        java -cp out MergeCSVs

    - name: Upload merged CSV
      uses: actions/upload-artifact@v3
      with:
        name: merged_data.csv
        path: ${{ env.CSV_FILE_PATH }}  # Utilisation de la variable d'environnement pour spécifier le chemin du fichier CSV

    - name: Add CSV files to .gitignore and remove from Git
      run: |
        echo "*.csv" >> .gitignore
        git rm --cached ${{ env.CSV_FILE_PATH }}
        git commit -m "Add CSV files to .gitignore and remove from Git"

    - name: Verify if the file is ignored
      run: |
        git check-ignore -v ${{ env.CSV_FILE_PATH }} || echo "The file is NOT ignored by .gitignore."
